#!/bin/bash

# This script downloads and runs the Pangolin installer.

echo "--- Starting Pangolin Installer Script ---"

# Step 1: Download and execute the initial installer script
echo "Attempting to download and run https://pangolin.net/get-installer.sh..."
if ! curl -fsSL https://pangolin.net/get-installer.sh | bash; then
    echo "Error: Failed to download or execute get-installer.sh."
    exit 1
fi
echo "get-installer.sh executed successfully (or completed without curl/bash errors)."

# Step 2: Run the installer generated by the previous step with sudo
# We assume the previous step created an executable named 'installer' in the current directory.
if [ -f "./installer" ]; then
    echo "Found ./installer. Running with sudo..."
    if ! sudo ./installer; then
        echo "Error: The sudo ./installer command failed."
        exit 1
    fi
    echo "sudo ./installer completed successfully."
else
    echo "Error: './installer' executable not found after running get-installer.sh."
    echo "Please check the output of the previous step for details."
    exit 1
fi

echo "--- Pangolin Installer Script Finished ---"
