version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    network_mode: 'host'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx-proxy-manager-data:/data
      - letsencrypt-certificates:/etc/letsencrypt

volumes:
  nginx-proxy-manager-data:
  letsencrypt-certificates:
